echo "copying JRCaptureScratch.*"
cp SimpleCaptureDemo/JRCapture/JRCaptureScratch.*                 Janrain/JRCapture/Classes/
echo "copying JRCapture.*"
cp SimpleCaptureDemo/JRCapture/JRCapture.*                        Janrain/JRCapture/Classes/
echo "copying JRCaptureData.*"
cp SimpleCaptureDemo/JRCapture/JRCaptureData.*                    Janrain/JRCapture/Classes/
echo "copying JRCaptureError.*"
cp SimpleCaptureDemo/JRCapture/JRCaptureError.*                   Janrain/JRCapture/Classes/
echo "copying JRCaptureTypes.*"
cp SimpleCaptureDemo/JRCapture/JRCaptureTypes.*                   Janrain/JRCapture/Classes/
echo "copying JRNSDate+ISO8601_CaptureDateTimeString*"
cp SimpleCaptureDemo/JRCapture/JRNSDate*                          Janrain/JRCapture/Classes/
echo "copying JRCaptureApidInterface.*"
cp SimpleCaptureDemo/JRCapture/JRCaptureApidInterface.*           Janrain/JRCapture/Classes/APIDInterface/
echo "copying JRCaptureObject.*"
cp SimpleCaptureDemo/JRCapture/JRCaptureObject.*                  Janrain/JRCapture/Classes/APIDInterface/
echo "copying JRCaptureObject+Internal.*"
cp SimpleCaptureDemo/JRCapture/JRCaptureObject+Internal.*         Janrain/JRCapture/Classes/APIDInterface/
echo "copying JRCaptureUser+Extras.*"
cp SimpleCaptureDemo/JRCapture/JRCaptureUser+Extras.*             Janrain/JRCapture/Classes/APIDInterface/
echo "copying JRApidWrapper.*"
cp SimpleCaptureDemo/JRCapture/JRApidWrapper.*                    Janrain/JRCapture/Classes/APIDInterface/
echo "copying JREngageWrapper.*"
cp SimpleCaptureDemo/JRCapture/JREngageWrapper.*                  Janrain/JRCapture/Classes/EngageWrapper/
echo "copying JRNativeSigninViewController.*"
cp SimpleCaptureDemo/JRCapture/JRNativeSigninViewController.*     Janrain/JRCapture/Classes/EngageWrapper/

echo "copying complete"
