echo "copying JRCapture.*"
cp Samples/SimpleCaptureDemo/JRCapture/JRCapture.*                           Janrain/JRCapture/Classes/
echo "copying JRCaptureError.*"
cp Samples/SimpleCaptureDemo/JRCapture/JRCaptureError.*                      Janrain/JRCapture/Classes/
echo "copying JRCaptureTypes.*"
cp Samples/SimpleCaptureDemo/JRCapture/JRCaptureTypes.*                      Janrain/JRCapture/Classes/
echo "copying JRCaptureData.*"
cp Samples/SimpleCaptureDemo/JRCapture/JRCaptureData.*                       Janrain/JRCapture/Classes/CaptureRecordInterface/
echo "copying JRNSDate+ISO8601_CaptureDateTimeString*"
cp Samples/SimpleCaptureDemo/JRCapture/JRNSDate*                             Janrain/JRCapture/Classes/CaptureRecordInterface/
echo "copying JRCaptureApidInterface.*"
cp Samples/SimpleCaptureDemo/JRCapture/JRCaptureApidInterface.*              Janrain/JRCapture/Classes/CaptureRecordInterface/
echo "copying JRCaptureObject.*"
cp Samples/SimpleCaptureDemo/JRCapture/JRCaptureObject.*                     Janrain/JRCapture/Classes/CaptureUserModel/
echo "copying JRCaptureObject+Internal.*"
cp Samples/SimpleCaptureDemo/JRCapture/JRCaptureObject+Internal.*            Janrain/JRCapture/Classes/CaptureUserModel/
echo "copying JRCaptureUser+Extras.*"
cp Samples/SimpleCaptureDemo/JRCapture/JRCaptureUser+Extras.*                Janrain/JRCapture/Classes/CaptureUserModel/
echo "copying JREngageWrapper.*"
cp Samples/SimpleCaptureDemo/JRCapture/JREngageWrapper.*                     Janrain/JRCapture/Classes/EngageWrapper/
echo "copying JRNativeSigninViewController.*"
cp Samples/SimpleCaptureDemo/JRCapture/JRConventionalSigninViewController.* Janrain/JRCapture/Classes/EngageWrapper/

echo "copying complete"
